title: LEGEND
logo: assets/img/logo.png
description: An integrative algorithm for identifying co-expressed and cofunctional genes in multi-omics.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
